image: docker:20.10
services:
  - docker:dind

before_script:
  - docker login gitlab.example.com:4567

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE: django_sql_img

stages:
  - build
  - test

build:
  stage: build
  before_script:
    # AWS CLIをインストール
    - apk add --update py-pip
    - pip install awscli
  script:
    # イメージのビルド
    - docker-compose build
    - docker save $DOCKER_IMAGE > $DOCKER_IMAGE.tar
  artifacts:
    #untracked: true
    paths:
      - $DOCKER_IMAGE.tar
  #only:
  #  - master

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apk add --update py-pip
  script:
    - docker load -i ${DOCKER_IMAGE}.tar
    - docker-compose run django_server pytest
  artifacts:
    paths:
      - $DOCKER_IMAGE.tar

