image: docker:20.10
services:
  - docker:dind

# 全てのジョブの前に実行するコスクリプト
before_script:
  - docker login gitlab.example.com:4567

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DIR_ON_OFF: ./func/on-off
  IMG_ON_OFF: img_on-off

stages:
  - test
  - deploy

test_lambda_function:
  stage: test
  before_script:
    - apk add --update py-pip
  script:
    # イメージのビルド&Test実行
    - docker build -f $DIR_ON_OFF/Dockerfile $DIR_ON_OFF/ -t $IMG_ON_OFF    
    - docker run $IMG_ON_OFF

# Deploy
deploy_lambda_function:
  image: node:18
  stage: deploy
  dependencies:
    - test_lambda_function
  before_script:
    - npm install -g serverless@3.35.2
    - npm install serverless-offline@13.2.0 --save-dev
    - npm install serverless-dotenv-plugin@6.0.0
  script:
    - serverless deploy --stage $STAGE
  only:
    - master

# Deploy
deploy_lambda_function_stg:
  image: node:18
  stage: deploy
  dependencies:
    - test_lambda_function
  before_script:
    - npm install -g serverless@3.35.2
    - npm install serverless-offline@13.2.0 --save-dev
    - npm install serverless-dotenv-plugin@6.0.0
  script:
    - serverless deploy --stage stg
  only:
    - master
