# Generated by Django 3.0 on 2023-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='good_point',
            field=models.IntegerField(default=0),
        ),
    ]
