# Generated by Django 3.0 on 2023-05-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myall', '0002_blog_good_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_blog', to='myall.Blog'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_tag', to='myall.Tag'),
        ),
    ]
