# Generated by Django 3.0 on 2023-05-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myall', '0004_mblog_mtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='利用額')),
                ('use_name', models.CharField(max_length=30, verbose_name='利用者')),
                ('lineid', models.CharField(max_length=30, verbose_name='Lineid')),
            ],
            options={
                'verbose_name': 'LINEPAY',
                'verbose_name_plural': 'LINEPAY',
                'db_table': 'GENERIC_ADJUSTMENT_LINEPAY',
            },
        ),
        migrations.CreateModel(
            name='PayPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='利用額')),
                ('use_name', models.CharField(max_length=30, verbose_name='利用者')),
            ],
            options={
                'verbose_name': 'PAYPAY',
                'verbose_name_plural': 'PAYPAY',
                'db_table': 'GENERIC_ADJUSTMENT_PAYPAY',
            },
        ),
        migrations.CreateModel(
            name='GenericAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '汎用精算',
                'verbose_name_plural': '汎用精算',
                'db_table': 'GENERIC_ADJUSTMENT',
            },
        ),
        migrations.AddIndex(
            model_name='genericadjustment',
            index=models.Index(fields=['content_type', 'object_id'], name='GENERIC_ADJ_content_7a0bf1_idx'),
        ),
    ]
