# Generated by Django 3.0 on 2023-07-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myall', '0005_auto_20230513_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='myall.Publication')),
            ],
        ),
    ]
