# Generated by Django 3.0 on 2023-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myall', '0008_auto_20230811_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
