# Generated by Django 3.2.4 on 2023-11-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myall', '0010_tag_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCompanyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=40)),
                ('disp_order', models.IntegerField(verbose_name='表示順序')),
            ],
            options={
                'verbose_name': 'サブ店舗タイプ',
                'db_table': 'sub_company_type',
            },
        ),
        migrations.AddField(
            model_name='subcompany',
            name='sub_company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myall.subcompanytype'),
        ),
    ]
